import { createRun, scoreAnswer, getRank, dailySeed, newSeed, normalizeSeed } from './engine.js';

const $ = (s) => document.querySelector(s);
const els = { start: $('#startView'), play: $('#playView'), result: $('#resultView'), startBtn: $('#startBtn'), again: $('#againBtn'), share: $('#shareBtn'), options: $('#options'), prompt: $('#prompt'), hint: $('#hint'), score: $('#score'), timer: $('#timer'), bar: $('#timerBar'), combo: $('#combo'), comboFire: $('#comboFire'), questionNo: $('#questionNo'), feedback: $('#feedback'), mascot: $('#mascot'), bubble: $('#bubble'), final: $('#finalScore'), rank: $('#rankChip'), rankDesc: $('#rankDesc'), right: $('#rightCount'), bestCombo: $('#bestCombo'), bestScore: $('#bestScore'), shareScore: $('#shareScore'), shareStatus: $('#shareStatus'), toast: $('#toast'), challengeNote: $('#challengeNote'), sound: $('#soundBtn'), help: $('#helpBtn'), dialog: $('#helpDialog'), closeHelp: $('#closeHelp') };
let run, seed, score = 0, combo = 0, maxCombo = 0, right = 0, questionNo = 0, seconds = 30, timerId, locked = false, soundOn = true;
const params = new URLSearchParams(location.search); const incomingSeed = params.get('challenge'); const incomingScore = Number(params.get('score'));
seed = normalizeSeed(incomingSeed || dailySeed());
if (incomingSeed) els.challengeNote.textContent = `朋友发来的挑战 · 题组 ${seed.slice(0, 12)}`;
else els.challengeNote.textContent = '今日题组已锁定 · 每个人拿到的题目一样';

function show(view){ [els.start,els.play,els.result].forEach(v=>v.classList.add('hidden')); view.classList.remove('hidden'); }
function beep(ok){ if(!soundOn) return; try { const C=window.AudioContext||window.webkitAudioContext; const c=new C(),o=c.createOscillator(),g=c.createGain(); o.frequency.value=ok?620:150;o.type=ok?'sine':'sawtooth';g.gain.value=.035;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+(ok?.07:.12)); } catch(e){} }
function setMascot(state){ els.mascot.src = state ? `assets/cat-${state}.svg` : 'assets/cat.svg'; }
function startGame(){ clearInterval(timerId); run=createRun(seed); score=0;combo=0;maxCombo=0;right=0;questionNo=0;seconds=30;locked=false; els.score.textContent='0';els.combo.textContent='0';els.timer.textContent='30';els.bar.style.width='100%';setMascot(''); nextQuestion();show(els.play); timerId=setInterval(tick,1000); }
function tick(){ seconds--; els.timer.textContent=String(Math.max(0,seconds)); els.bar.style.width=`${Math.max(0,seconds/30*100)}%`; if(seconds<=0) endGame(); }
function optionVisual(o){ if(o.kind==='cat') return `<span class="cat-face ${o.size}">🐱</span><span class="option-sub">${o.size==='large'?'大猫':'小猫'}</span>`; if(o.kind==='number') return `<span class="num-face">${o.value}</span><span class="option-sub">数字</span>`; if(o.kind==='color') return `<span class="color-swatch" style="background:${o.color}"></span><span class="option-sub">${o.color==='red'?'红色':'蓝色'}</span>`; if(o.kind==='count') return `<span class="cat-face">${'🐱'.repeat(o.count)}</span><span class="option-sub">${o.count} 只</span>`; if(o.kind==='word') return `<span class="word-face" style="color:${o.color}">${o.value}</span><span class="option-sub">看字，不看颜色</span>`; return `<span class="option-label">${o.label}</span><span class="option-sub">${o.value==='left'?'左边':'右边'}</span>`; }
function nextQuestion(){ const q=run.next(); questionNo++; locked=false; els.questionNo.textContent=`第 ${questionNo} 题`;els.prompt.textContent=q.prompt;els.hint.textContent=q.hint;els.options.innerHTML=q.options.map((o,i)=>`<button class="option" data-index="${i}" aria-label="${o.label}">${optionVisual(o)}</button>`).join(''); els.options.querySelectorAll('.option').forEach((b)=>b.addEventListener('click',()=>answer(Number(b.dataset.index),q))); }
function answer(index,q){ if(locked||seconds<=0)return; locked=true; const ok=index===q.correctIndex; const buttons=[...els.options.children];buttons[index].classList.add(ok?'correct':'wrong'); beep(ok); if(ok){ const reward=scoreAnswer(combo); combo=reward.nextCombo;score+=reward.points;right++;maxCombo=Math.max(maxCombo,combo);els.feedback.textContent=`${q.explanation}  +${reward.points}`;els.comboFire.textContent=combo>=3?'🔥':'';setMascot(combo>=6?'smug':''); } else { combo=0; seconds=Math.max(0,seconds-2);els.feedback.textContent=`${q.explanation}  -2 秒`;els.comboFire.textContent='';setMascot('shock'); buttons[q.correctIndex].classList.add('correct'); } els.score.textContent=score;els.combo.textContent=combo;setTimeout(()=>{ if(seconds>0)nextQuestion(); },ok?135:400); }
function endGame(){ clearInterval(timerId);seconds=0;els.timer.textContent='0';locked=true;const old=Number(localStorage.getItem('rebel-cat-best')||0);const best=Math.max(old,score);localStorage.setItem('rebel-cat-best',best);const rank=getRank(score);els.final.textContent=score;els.rank.textContent=`${rank.emoji} ${rank.name}`;els.rankDesc.textContent=rank.description;els.right.textContent=right;els.bestCombo.textContent=maxCombo;els.bestScore.textContent=best;els.shareScore.textContent=score;setMascot(score>=100?'smug':'');show(els.result); }
async function share(){ const url=`${location.origin}${location.pathname}?challenge=${encodeURIComponent(seed)}&score=${score}`; const text=`我在《反骨小猫》拿了 ${score} 分！你能比我更反骨吗？`;try{ if(navigator.share){await navigator.share({title:'反骨小猫',text,url});els.shareStatus.textContent='已打开分享面板'; } else {await navigator.clipboard.writeText(url);els.shareStatus.textContent='挑战链接已复制，发给朋友吧！'; } }catch(e){ try{await navigator.clipboard.writeText(url);els.shareStatus.textContent='链接已复制，发给朋友吧！';}catch(_){els.shareStatus.textContent=url;} }showToast('挑战链接已准备好 ↗'); }
function showToast(t){els.toast.textContent=t;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),1800)}
els.startBtn.addEventListener('click',startGame);els.again.addEventListener('click',()=>{seed=newSeed();startGame()});els.share.addEventListener('click',share);els.sound.addEventListener('click',()=>{soundOn=!soundOn;els.sound.textContent=soundOn?'🔊':'🔇';els.sound.setAttribute('aria-pressed',String(soundOn))});els.help.addEventListener('click',()=>els.dialog.showModal());els.closeHelp.addEventListener('click',()=>els.dialog.close());els.dialog.addEventListener('click',(e)=>{if(e.target===els.dialog)els.dialog.close()});window.addEventListener('keydown',(e)=>{ if(!els.play.classList.contains('hidden')&&!locked&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault(); const idx=e.key==='ArrowLeft'?0:1; const button=els.options.children[idx]; if(button)button.click(); } });
