import { createRun, scoreAnswer, getRank, dailySeed, newSeed, normalizeSeed } from './engine.js?v=2';
import { makeScoreCard } from './card.js';

const $ = (s) => document.querySelector(s);
const els = { start: $('#startView'), play: $('#playView'), result: $('#resultView'), startBtn: $('#startBtn'), again: $('#againBtn'), share: $('#shareBtn'), options: $('#options'), prompt: $('#prompt'), hint: $('#hint'), score: $('#score'), timer: $('#timer'), bar: $('#timerBar'), combo: $('#combo'), comboFire: $('#comboFire'), questionNo: $('#questionNo'), feedback: $('#feedback'), mascot: $('#mascot'), bubble: $('#bubble'), final: $('#finalScore'), rank: $('#rankChip'), rankDesc: $('#rankDesc'), right: $('#rightCount'), bestCombo: $('#bestCombo'), bestScore: $('#bestScore'), shareScore: $('#shareScore'), shareStatus: $('#shareStatus'), toast: $('#toast'), challengeNote: $('#challengeNote'), sound: $('#soundBtn'), help: $('#helpBtn'), dialog: $('#helpDialog'), closeHelp: $('#closeHelp') };
let run, seed, score = 0, combo = 0, maxCombo = 0, right = 0, questionNo = 0, seconds = 30, timerId, nextId, deadline = 0, playing = false, locked = false, soundOn = true;
const params = new URLSearchParams(location.search); const incomingSeed = params.get('challenge'); const incomingScore = Number(params.get('score'));
seed = normalizeSeed(incomingSeed || dailySeed());
if (incomingSeed) { els.challengeNote.textContent = `朋友拿了 ${Number.isFinite(incomingScore)?Math.max(0,Math.min(99999,incomingScore)):0} 分，敢接招吗？`; els.startBtn.firstChild.textContent='接受挑战 '; }
else els.challengeNote.textContent = '今日题组已锁定 · 每个人拿到的题目一样';

function show(view){ [els.start,els.play,els.result].forEach(v=>v.classList.add('hidden')); view.classList.remove('hidden'); }
function beep(ok){ if(!soundOn) return; try { const C=window.AudioContext||window.webkitAudioContext; const c=new C(),o=c.createOscillator(),g=c.createGain(); o.onended=()=>c.close(); o.frequency.value=ok?620:150;o.type=ok?'sine':'sawtooth';g.gain.value=.035;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+(ok?.07:.12)); } catch(e){} }
function setMascot(state){ els.mascot.src = state ? `assets/cat-${state}.svg` : 'assets/cat.svg'; }
function startGame(){ clearInterval(timerId);clearTimeout(nextId);playing=true;deadline=performance.now()+30000;els.feedback.textContent='';els.comboFire.textContent='';els.shareStatus.textContent='';run=createRun(seed); score=0;combo=0;maxCombo=0;right=0;questionNo=0;seconds=30;locked=false; els.score.textContent='0';els.combo.textContent='0';els.timer.textContent='30';els.bar.style.width='100%';setMascot(''); nextQuestion();show(els.play); timerId=setInterval(tick,100); }
function tick(){ if(!playing)return;seconds=Math.max(0,(deadline-performance.now())/1000);els.timer.textContent=String(Math.ceil(seconds));els.bar.style.width=`${seconds/30*100}%`;if(seconds<=0)endGame(); }
function optionVisual(o){ if(o.kind==='cat') return `<img class="option-cat ${o.size}" src="assets/cat.svg" alt="" /><span class="option-sub">${o.size==='large'?'大猫':'小猫'}</span>`; if(o.kind==='number') return `<span class="num-face">${o.value}</span><span class="option-sub">数字</span>`; if(o.kind==='color') return `<span class="color-swatch" style="background:${o.color}"></span><span class="option-sub">${o.color==='red'?'红色':'蓝色'}</span>`; if(o.kind==='count') return `<span class="count-cats">${'<img src="assets/cat.svg" alt="" />'.repeat(o.count)}</span><span class="option-sub">${o.count} 只</span>`; if(o.kind==='word') return `<span class="word-face" style="color:${o.color}">${o.value}</span><span class="option-sub">看字，不看颜色</span>`; return `<span class="option-label">${o.label}</span><span class="option-sub">${o.value==='left'?'左边':'右边'}</span>`; }
function nextQuestion(){ const q=run.next(); questionNo++; locked=false; els.questionNo.textContent=`第 ${questionNo} 题`;els.prompt.textContent=q.prompt;els.hint.textContent=q.hint;els.options.innerHTML=q.options.map((o,i)=>`<button class="option" data-index="${i}" aria-label="${o.label}">${optionVisual(o)}</button>`).join(''); els.options.querySelectorAll('.option').forEach((b)=>b.addEventListener('click',()=>answer(Number(b.dataset.index),q))); }
function answer(index,q){ tick();if(locked||!playing||seconds<=0)return; locked=true; const ok=index===q.correctIndex; const buttons=[...els.options.children];buttons[index].classList.add(ok?'correct':'wrong'); beep(ok); if(ok){ const reward=scoreAnswer(combo); combo=reward.nextCombo;score+=reward.points;right++;maxCombo=Math.max(maxCombo,combo);els.feedback.textContent=`${q.explanation}  +${reward.points}`;els.comboFire.textContent=combo>=3?'🔥':'';setMascot(combo>=6?'smug':''); } else { combo=0; deadline-=2000;seconds=Math.max(0,(deadline-performance.now())/1000);els.feedback.textContent=`${q.explanation}  -2 秒`;els.comboFire.textContent='';setMascot('shock'); buttons[q.correctIndex].classList.add('correct'); } els.score.textContent=score;els.combo.textContent=combo;if(seconds<=0){endGame();return;}nextId=setTimeout(()=>{if(playing)nextQuestion();},ok?150:500); }
function endGame(){ if(!playing)return;playing=false;clearInterval(timerId);clearTimeout(nextId);seconds=0;els.timer.textContent='0';locked=true;let old=0;try{old=Number(localStorage.getItem('rebel-cat-best')||0)||0;}catch(e){}const best=Math.max(old,score);try{localStorage.setItem('rebel-cat-best',best);}catch(e){}const rank=getRank(score);els.final.textContent=score;els.rank.textContent=`${rank.emoji} ${rank.name}`;els.rankDesc.textContent=incomingSeed ? (score>incomingScore?`超过朋友 ${score-incomingScore} 分！轮到他来追你了。`:score===incomingScore?'和朋友打成平手！再来一次？':`还差 ${incomingScore-score} 分追平朋友，再来一次！`) : rank.description;els.right.textContent=right;els.bestCombo.textContent=maxCombo;els.bestScore.textContent=best;els.shareScore.textContent=score;setMascot(score>=100?'smug':'');show(els.result); }
function challengeUrl(){return `${location.origin}${location.pathname}?challenge=${encodeURIComponent(seed)}&score=${score}`;}
async function share(){ const url=challengeUrl();try{await navigator.clipboard.writeText(url);els.shareStatus.textContent='挑战链接已复制，发给朋友吧！';showToast('链接已复制 ✓');}catch(e){const input=document.createElement('input');input.value=url;input.readOnly=true;input.style.width='100%';els.shareStatus.replaceChildren(input);input.select();showToast('长按链接即可复制');}}
async function card(){try{const result=await makeScoreCard({score,rankName:getRank(score).name,correct:right,maxCombo,url:challengeUrl(),seed});document.querySelector('#cardImage').src=result.dataUrl;document.querySelector('#downloadCard').href=result.dataUrl;document.querySelector('#cardDialog').showModal();}catch(e){showToast('图片生成失败，请复制挑战链接');}}
document.querySelector('#cardBtn').addEventListener('click',card);
document.querySelector('#closeCard').addEventListener('click',()=>document.querySelector('#cardDialog').close());
function showToast(t){els.toast.textContent=t;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),1800)}
els.startBtn.addEventListener('click',startGame);els.again.addEventListener('click',()=>{startGame()});els.share.addEventListener('click',share);els.sound.addEventListener('click',()=>{soundOn=!soundOn;els.sound.textContent=soundOn?'🔊':'🔇';els.sound.setAttribute('aria-pressed',String(soundOn))});els.help.addEventListener('click',()=>els.dialog.showModal());els.closeHelp.addEventListener('click',()=>els.dialog.close());els.dialog.addEventListener('click',(e)=>{if(e.target===els.dialog)els.dialog.close()});window.addEventListener('keydown',(e)=>{ if(!els.play.classList.contains('hidden')&&!els.dialog.open&&!locked&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault(); const idx=e.key==='ArrowLeft'?0:1; const button=els.options.children[idx]; if(button)button.click(); } });
